/**:
  ros__parameters:

    base_link:
      mass: 5.0
      size: [0.5, 0.5, 0.1] # x, y, z
      offset_z: 0.0973
      nav_offset_x: 0.032
      nav_offset_z: 0.0


    nav_module:
      offset_x: 0.032
      offset_z: 0.0


    imu:
      name: "imu"
      topic: "/imu/data"
      frame_id: "imu_link"
    

    lidar:
      name: "lidar"
      topic: "/scan"
      frame_id: "lidar_link"
      range_min: 0.1
      range_max: 10.0
      fov: 360
      resolution: 1.0


    flow_sensor:
      name: "flow_front"
      topic: "/flow/front"
      frame_id: "flow_front_link"
      offset: [0.3, 0.0, 0.0] # x, y, z
      yaw: 0.0


    bumpers:
      - name: "front"
        pin: 0
        inverted: false # true=NC, false=NO
        size: [0.02, 0.4, 0.05] # x, y, z (depth, width, height)
        offset: [0.2, 0.0, 0.0] # x, y, z
        yaw: 0.0
        parent_frame: "base_link"

      - name: "rear"
        pin: 1
        inverted: false
        size: [0.02, 0.4, 0.05]
        offset: [-0.2, 0.0, 0.0]
        yaw: 3.14
        parent_frame: "base_link"

      - name: "left"
        pin: 2
        inverted: false
        size: [0.02, 0.3, 0.05]
        offset: [0.0, 0.2, 0.0]
        yaw: 1.57
        parent_frame: "base_link"

      - name: "right"
        pin: 3
        inverted: false
        size: [0.02, 0.3, 0.05]
        offset: [0.0, -0.2, 0.0]
        yaw: -1.57
        parent_frame: "base_link"


    cliff_sensors:
      - name: "fl"
        pin: 0
        size: [0.02, 0.02, 0.05]
        offset: [0.3, 0.3, 0.0] # x, y, z
        yaw: 0.0
        parent_frame: "base_link"

      - name: "fr"
        pin: 1
        size: [0.02, 0.02, 0.05]
        offset: [0.3, -0.3, 0.0]
        yaw: 0.0
        parent_frame: "base_link"

      - name: "rl"
        pin: 2
        size: [0.02, 0.02, 0.05]
        offset: [-0.3, 0.3, 0.0]
        yaw: 3.14
        parent_frame: "base_link"

      - name: "rr"
        pin: 3
        size: [0.02, 0.02, 0.05]
        offset: [-0.3, -0.3, 0.0]
        yaw: 3.14
        parent_frame: "base_link"