# cmd_vel safe (ROS -> GZ)
- ros_topic_name: "/cmd_vel_safe"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Clock (GZ -> ROS)
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Lidar (GZ -> ROS)
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Odometrie (GZ -> ROS)
- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# IMU data (GZ -> ROS)
- ros_topic_name: "/imu/data"
  gz_topic_name: "/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Joint states (GZ -> ROS)
- ros_topic_name: "/joint_states"
  gz_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# # TF transformace (GZ -> ROS)
# - ros_topic_name: "/tf"
#   gz_topic_name: "/tf"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS

# Cliff sensors - corners (GZ -> ROS) [sensor_msgs/msg/Range]
# - ros_topic_name: "/cliff/front_left"
#   gz_topic_name: "/cliff/front_left"
#   ros_type_name: "sensor_msgs/msg/Range"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/cliff/front_right"
#   gz_topic_name: "/cliff/front_right"
#   ros_type_name: "sensor_msgs/msg/Range"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/cliff/rear_left"
#   gz_topic_name: "/cliff/rear_left"
#   ros_type_name: "sensor_msgs/msg/Range"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/cliff/rear_right"
#   gz_topic_name: "/cliff/rear_right"
#   ros_type_name: "sensor_msgs/msg/Range"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS

# # Bumper senzory (GZ -> ROS)  [std_msgs/msg/Bool]
# - ros_topic_name: "/bumper/front/contact"
#   gz_topic_name: "/world/my_world/model/my_robot/link/bumper_front_contact/sensor/bumper_front_sensor/contact"
#   ros_type_name: "ros_gz_interfaces/msg/Contacts"
#   gz_type_name: "gz.msgs.Contacts"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/bumper/rear/contact"
#   gz_topic_name: "/world/my_world/model/my_robot/link/bumper_rear_contact/sensor/bumper_rear_sensor/contact"
#   ros_type_name: "ros_gz_interfaces/msg/Contacts"
#   gz_type_name: "gz.msgs.Contacts"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/bumper/left/contact"
#   gz_topic_name: "/world/my_world/model/my_robot/link/bumper_left_contact/sensor/bumper_left_sensor/contact"
#   ros_type_name: "ros_gz_interfaces/msg/Contacts"
#   gz_type_name: "gz.msgs.Contacts"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/bumper/right/contact"
#   gz_topic_name: "/world/my_world/model/my_robot/link/bumper_right_contact/sensor/bumper_right_sensor/contact"
#   ros_type_name: "ros_gz_interfaces/msg/Contacts"
#   gz_type_name: "gz.msgs.Contacts"
#   direction: GZ_TO_ROS