/**:
  ros__parameters:

    visual_colors:
      base: [0.24, 0.26, 0.29, 1.0]
      main_module: [0.42, 0.45, 0.49, 1.0]
      wheel: [0.10, 0.10, 0.11, 1.0]
      imu_mount: [0.50, 0.28, 0.92, 1.0]
      lidar_mount: [0.20, 0.48, 0.72, 1.0]
      bumper_mount: [0.68, 0.20, 0.20, 1.0]
      cliff_mount: [0.18, 0.62, 0.44, 1.0]

    base_link:
      mass: 5.0
      size: [0.35, 0.38, 0.05]
      offset_z: 0.100

    nav_module:
      size: [0.24, 0.18, 0.06]
      offset: [0.05, 0.0, 0.06]
      rpy: [0.0, 0.0, 0.0]

    drive:
      mode: 'mecanum' # mecanum | diff

    wheels:
      wheelbase: 0.24
      track_width: 0.38
      radius: 0.055
      length: 0.03
      offset_z: -0.06
      mu: 1.1
      mu2: 0.15

    imu:
      enabled: true
      type: 'imu'
      name: 'imu'
      topic: '/imu/data'
      update_rate: 100
      visualize: false
      frame_id: 'imu_link'
      size: [0.05, 0.05, 0.01]
      mount_parent_frame: 'main_module_mount'
      mount_offset: [-0.01, 0.05, 0.03]
      mount_rpy: [0.0, 0.0, 0.0]
      offset: [0.0, 0.0, 0.03]
      rpy: [0.0, 0.0, 0.0]

    lidar:
      enabled: true
      name: 'lidar'
      topic: '/scan'
      update_rate: 10
      visualize: false
      frame_id: 'lidar_beam'
      size: [0.08, 0.02] # [diameter, height]
      mount_parent_frame: 'main_module_mount'
      mount_offset: [0.07, 0.0, 0.03]
      mount_rpy: [0.0, 0.0, 0.0]
      angle_min: 0.0
      angle_max: 6.28319
      range_min: 0.1
      range_max: 10.0
      fov: 360
      resolution: 1.0
      offset: [0.0, 0.0, 0.02]
      rpy: [0.0, 0.0, 0.0]

    bumpers:
      - name: 'front'
        enabled: true
        inverted: false
        update_rate: 30
        size: [0.03, 0.45, 0.06]
        mount_parent_frame: 'base_link'
        mount_offset: [0.32, 0.0, 0.0]
        mount_rpy: [0.0, 0.0, 0.0]
        contact_offset: [0.031, 0.0, -0.03]
        contact_outset: 0.001
        contact_rpy: [0.0, 0.0, 0.0]

      - name: 'rear'
        enabled: true
        inverted: false
        update_rate: 30
        size: [0.03, 0.45, 0.06]
        mount_parent_frame: 'base_link'
        mount_offset: [-0.32, 0.0, 0.0]
        mount_rpy: [0.0, 0.0, 3.14159]
        contact_offset: [0.031, 0.0, -0.03]
        contact_outset: 0.001
        contact_rpy: [0.0, 0.0, 0.0]

      - name: 'left'
        enabled: true
        inverted: false
        update_rate: 30
        size: [0.03, 0.4, 0.06]
        mount_parent_frame: 'base_link'
        mount_offset: [0.0, 0.25, 0.0]
        mount_rpy: [0.0, 0.0, 1.5708]
        contact_offset: [0.031, 0.0, -0.03]
        contact_outset: 0.001
        contact_rpy: [0.0, 0.0, 0.0]

      - name: 'right'
        enabled: true
        inverted: false
        update_rate: 30
        size: [0.03, 0.4, 0.06]
        mount_parent_frame: 'base_link'
        mount_offset: [0.0, -0.25, 0.0]
        mount_rpy: [0.0, 0.0, -1.5708]
        contact_offset: [0.031, 0.0, -0.03]
        contact_outset: 0.001
        contact_rpy: [0.0, 0.0, 0.0]

    cliff_sensors:
      - name: 'fl'
        enabled: true
        topic: '/cliff/fl'
        update_rate: 20
        visualize: true
        range_min: 0.01
        range_max: 0.5
        range_resolution: 0.001
        size: [0.02, 0.04, 0.03]
        mount_parent_frame: 'base_link'
        mount_offset: [0.24, 0.2, -0.045]
        mount_rpy: [0.0, 0.0, 0.0]
        beam_offset: [0.01, 0.0, -0.02]
        beam_rpy: [0.0, 1.5708, 0.0]

      - name: 'fr'
        enabled: true
        topic: '/cliff/fr'
        update_rate: 20
        visualize: true
        range_min: 0.01
        range_max: 0.5
        range_resolution: 0.001
        size: [0.02, 0.04, 0.03]
        mount_parent_frame: 'base_link'
        mount_offset: [0.24, -0.2, -0.045]
        mount_rpy: [0.0, 0.0, 0.0]
        beam_offset: [0.01, 0.0, -0.02]
        beam_rpy: [0.0, 1.5708, 0.0]

      - name: 'rl'
        enabled: true
        topic: '/cliff/rl'
        update_rate: 20
        visualize: true
        range_min: 0.01
        range_max: 0.5
        range_resolution: 0.001
        size: [0.02, 0.02, 0.02]
        mount_parent_frame: 'base_link'
        mount_offset: [-0.24, 0.2, -0.045]
        mount_rpy: [0.0, 0.0, 3.14159]
        beam_offset: [0.01, 0.0, -0.02]
        beam_rpy: [0.0, 1.5708, 0.0]

      - name: 'rr'
        enabled: true
        topic: '/cliff/rr'
        update_rate: 20
        visualize: true
        range_min: 0.01
        range_max: 0.5
        range_resolution: 0.001
        size: [0.02, 0.02, 0.02]
        mount_parent_frame: 'base_link'
        mount_offset: [-0.24, -0.2, -0.045]
        mount_rpy: [0.0, 0.0, 3.14159]
        beam_offset: [0.01, 0.0, -0.02]
        beam_rpy: [0.0, 1.5708, 0.0]
