lidar_node:
  ros__parameters:
    frame_id: 'lidar_mount'
    angle_min: 0.0
    angle_max: 6.28319
    range_max: 5.0
    range_min: 0.05
    port: '/dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.2:1.0-port0'
    motor_pin: 19
    frequency: 10000
    target_rpm: 300

motors_node:
  ros__parameters:
    port: '/dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0'
    max_speed: 255

display_node:
  ros__parameters:
    width: 128
    height: 32
    orientation: 2
    brightness: 5

fan_control_node:
  ros__parameters:
    fan_pin: 13
    frequency: 10
    min_to_run: 0.25
    user_power: [0.0, 0.5, 1.0]

sharp_sensors_node:
  ros__parameters:
    v_points: [0.3, 0.4, 0.8, 1.2, 2.0, 2.5]
    d_points: [0.20, 0.15, 0.08, 0.05, 0.03, 0.02]

optical_flow_node:
  ros__parameters:
    spi_port: 0
    spi_cs: 0
    deadzone: 3
    timer_period: 0.05
    sensor_frame: 'flow_sensor_link'
    z_height: 0.025
    fov_deg: 42.0
    res_pix: 35
